server:
  port: 7001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # whether this service want to be discovered in eureka server
    register-with-eureka: false
    # whether this client should fetch eureka registry information from eureka
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
