server:
  port: 8003

spring:
  application:
    name: order-feign-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: order-feign-client
    prefer-ip-address: true
